# Generated by Django 4.2.13 on 2024-05-18 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
